Algoritmo "exercicio 11"



Var

n1,n2,n3, p1,p2,p3, mp : real

Inicio

     escreval ("digite nota1: ")
     leia (n1)
     escreval ("digite peso1: ")
     leia (p1)
     escreval ("digite nota2: ")
     leia (n2)
     escreval ("digite peso2: ")
     leia (p2)
     escreval ("digite nota3: ")
     leia (n3)
     escreval ("digite peso3: ")
     leia (p3)


     
    mp <- (n1*p1*n2*p2*n3*p3)/(p1+p2+p3)

    escreval ("a media ponderada é de : ",mp)



Fimalgoritmo